# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20171022_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('commercial', 'Commercial'), ('public', 'Public')], default='public', max_length=255),
            preserve_default=False,
        ),
    ]
